/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CourseController;

/**
 *
 * @author hp
 */
public class Course extends javax.swing.JFrame {

    /**
     * Creates new form Course
     */
    public Course() {
        initComponents();
    }
        public void clearField() {
  courseTF.setText("");
 cnameTF.setText("");
 sixRbtn.setSelected(true);
 yearRbtn.setSelected(true);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        courseTF = new javax.swing.JTextField();
        cnameTF = new javax.swing.JTextField();
        paymentCbtn = new javax.swing.JComboBox<>();
        sixRbtn = new javax.swing.JRadioButton();
        yearRbtn = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Course Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 0, 227, 44);

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(500, 350, 73, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 100, 61, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 150, 90, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Duration");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 200, 70, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Payment Method");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 240, 110, 20);

        courseTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseTFActionPerformed(evt);
            }
        });
        jPanel1.add(courseTF);
        courseTF.setBounds(280, 90, 268, 20);
        jPanel1.add(cnameTF);
        cnameTF.setBounds(280, 140, 270, 20);

        paymentCbtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Online Transfer" }));
        paymentCbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentCbtnActionPerformed(evt);
            }
        });
        jPanel1.add(paymentCbtn);
        paymentCbtn.setBounds(270, 240, 99, 20);

        sixRbtn.setText("Six Month");
        sixRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixRbtnActionPerformed(evt);
            }
        });
        jPanel1.add(sixRbtn);
        sixRbtn.setBounds(270, 190, 73, 23);

        yearRbtn.setText("A Year");
        jPanel1.add(yearRbtn);
        yearRbtn.setBounds(420, 190, 57, 23);

        submitBtn.setBackground(new java.awt.Color(255, 0, 0));
        submitBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn);
        submitBtn.setBounds(280, 350, 100, 27);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/istockphoto-1631061201-612x612.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 40, 630, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void courseTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseTFActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_courseTFActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
  
         SearchCourse d= new SearchCourse ();
     d.setVisible(true);
     this.setVisible(false);
        
        
        CourseController.Course(courseTF.getText(), cnameTF.getText());
        clearField();

    }//GEN-LAST:event_submitBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                   Home g = new Home ();
     g.setVisible(true);
     this.setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void paymentCbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentCbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentCbtnActionPerformed

    private void sixRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixRbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sixRbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cnameTF;
    private javax.swing.JTextField courseTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> paymentCbtn;
    private javax.swing.JRadioButton sixRbtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JRadioButton yearRbtn;
    // End of variables declaration//GEN-END:variables

    //To change body of generated methods, choose Tools | Templates.
    }

